platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
# 忽略引入库的所有警告（强迫症者的福音啊）
inhibit_all_warnings!

target 'mobikoo' do
  # 网络请求
  pod 'Alamofire'
  #pod 'Moya/RxSwift'    # 用于网络请求
  pod 'Moya'
  pod 'SnapKit'  #自动布局
  pod 'Kingfisher' # SDWebImage swift 版
  pod 'IQKeyboardManagerSwift'
  pod 'SwiftyJSON'

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxGesture' #对view手势的封装     
  #pod 'RxDataSources', '~> 3.0'  # RxSwift中用于设置UITableView/UICollectionView data sources

  #pod 'SwifterSwift' # 常用拓展
  pod 'ESTabBarController-swift' # TabBar
  pod 'EmptyDataSet-Swift' #  列表空数据图文展示
  pod 'SwiftyFitsize' # 字体适配
  pod 'SKPhotoBrowser' # 图片预览
  pod 'JXSegmentedView' # 分类滚动
    
  # OC
  pod 'MBProgressHUD'
  pod 'MJRefresh'
  pod 'TZImagePickerController' # 相册获取图片或视频
  #pod 'FSCalendar' # 日期选择
  pod "PYSearch" # 搜索controller
  #pod 'YPNavigationBarTransition' # NavBar
  #pod 'YYText'
  
end

